# Generated by Django 2.0.3 on 2018-04-08 17:52

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('telephone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2018, 4, 8, 17, 52, 23, 596201))),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[('NEW', 'NOT ASSIGNED'), ('ASSIGNED', 'ASSIGNED'), ('FINISHED', 'FINISHED'), ('CLOSED', 'CLOSED')], default='NEW', max_length=256)),
                ('table', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(15)])),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2018, 4, 8, 17, 52, 23, 596201))),
                ('due_date', models.DateTimeField(default=datetime.datetime(2018, 4, 8, 18, 22, 23, 596201))),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned', to='oms.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=1024)),
                ('price', models.PositiveIntegerField()),
                ('active', models.BooleanField()),
                ('quantity', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2018, 4, 8, 17, 52, 23, 596201))),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='oms.Product'),
        ),
    ]
