# Generated by Django 2.0.3 on 2018-06-17 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0003_auto_20180617_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 17, 19, 21, 3, 381013)),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 17, 18, 51, 3, 381013)),
        ),
        migrations.AlterField(
            model_name='product',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 17, 18, 51, 3, 365389)),
        ),
    ]
