# Generated by Django 2.0.3 on 2018-04-08 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0004_auto_20180408_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 8, 18, 14, 59, 816075)),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 8, 18, 44, 59, 816075)),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 8, 18, 14, 59, 816075)),
        ),
        migrations.AlterField(
            model_name='product',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 8, 18, 14, 59, 816075)),
        ),
    ]
