# Generated by Django 2.0.3 on 2018-04-08 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0005_auto_20180408_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 8, 18, 56, 19, 804825)),
        ),
        migrations.AlterField(
            model_name='order',
            name='Status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('ASSIGNED', 'ASSIGNED'), ('FINISHED', 'FINISHED'), ('CLOSED', 'CLOSED')], default='NEW', max_length=256),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 8, 19, 26, 19, 805823)),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 8, 18, 56, 19, 805823)),
        ),
        migrations.AlterField(
            model_name='product',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 8, 18, 56, 19, 803825)),
        ),
    ]
