# Generated by Django 2.0.3 on 2018-04-08 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0006_auto_20180408_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 8, 19, 9, 12, 953198)),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 8, 19, 39, 12, 954698)),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 8, 19, 9, 12, 954198)),
        ),
        migrations.AlterField(
            model_name='product',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 8, 19, 9, 12, 952199)),
        ),
    ]
