# Generated by Django 2.0.3 on 2018-05-16 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0008_auto_20180516_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 16, 23, 25, 43, 182630)),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 16, 22, 55, 43, 182630)),
        ),
        migrations.AlterField(
            model_name='product',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 16, 22, 55, 43, 182630)),
        ),
    ]
