# Generated by Django 2.0.3 on 2018-05-16 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0009_auto_20180516_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 16, 23, 32, 9, 421708)),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 16, 23, 2, 9, 421708)),
        ),
        migrations.AlterField(
            model_name='product',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 16, 23, 2, 9, 418778)),
        ),
    ]
